openapi: 3.0.0
info:
  title: API de Credenciales Verificables
  version: 1.0.0
  description: API para la emisión y verificación de credenciales verificables utilizando OpenID4VC.
servers:
  - url: http://localhost:3000
paths:
  /issuer/createCredentialOffer:
    post:
      summary: Crea una oferta de credencial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialType:
                  type: string
                  description: Tipo de credencial (ej TantanCredential)
                metadata:
                  type: object
                  description: Metadatos de la credencial
      responses:
        200:
          description: Oferta de credencial creada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  credentialOffer:
                    type: string
                    description: URI de la oferta de credencial
                  issuanceSession:
                    type: object
                    description: Información de la sesión de emisión
        500:
          description: Error interno del servidor
  /holder/resolveCredentialOffer:
    post:
      summary: Resuelve una oferta de credencial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialOffer:
                  type: string
                  description: URI de la oferta de credencial
      responses:
        200:
          description: Oferta de credencial resuelta correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  resolvedCredentialOffer:
                    type: object
                    description: Información detallada de la oferta de credencial
                  credentialsToRequest:
                    type: array
                    description: Lista de IDs de credenciales que se pueden solicitar
        500:
          description: Error interno del servidor
  /holder/requestCredential:
    post:
      summary: Solicita una credencial
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resolvedCredentialOffer:
                  type: object
                  description: Información detallada de la oferta de credencial resuelta
                credentialsToRequest:
                  type: array
                  description: Lista de IDs de credenciales que se van a solicitar
      responses:
        200:
          description: Credencial solicitada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
                  credentials:
                    type: array
                    description: Lista de credenciales obtenidas
        500:
          description: Error interno del servidor
  /verifier/createProofRequest:
    post:
      summary: Crea una solicitud de prueba (presentación)
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                credentialType:
                  type: string
                  description: Tipo de credencial (ej TantanCredential)
      responses:
        200:
          description: Solicitud de prueba creada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  proofRequestUri:
                    type: object
                    description: Objeto con la url de la petición
        500:
          description: Error interno del servidor
  /holder/resolveProofRequest:
    post:
      summary: Resuelve una solicitud de prueba
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                proofRequestUri:
                  type: string
                  description: URI de la solicitud de prueba
      responses:
        200:
          description: Solicitud de prueba resuelta correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje informativo
                  presentationPurpose:
                    type: string
                    description: El proposito de la presentación
                  credentialsReady:
                    type: boolean
                    description: Si existen credenciales disponibles que satisfagan la petición
                  stateId:
                    type: string
                    description: Id del estado de la solicitud
        500:
          description: Error interno del servidor
  /holder/acceptPresentationRequest:
    post:
      summary: Acepta una solicitud de presentación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                stateId:
                  type: string
                  description: Identificador del estado de la solicitud de presentación
      responses:
        200:
          description: Solicitud de presentación aceptada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Mensaje de éxito
                  acceptPresentationRequestResponse:
                    type: object
                    description: Información detallada de la respuesta de aceptación
        500:
          description: Error interno del servidor
  /health/live:
    get:
      summary: Ruta para verificar que la API está funcionando
      responses:
        200:
          description: API funcionando correctamente
          content:
            text/plain:
              schema:
                type: string
                example: OK
